### ISSUE TITLE
Support for youtu.be links 

### ISSUE THREAD

**Issue by nullstalgia** [bspammer/twitch-chat-replay#112]
When I use the site on mobile, I often get videos from the YouTube app, which gives these shortened URLs that expand when navigated to.

Needing to paste it into a regular browser to expand the link first isn't the most user-friendly :P

Example link:
 https://youtu.be/OaxlJC9wTl4

**Comment by bspammer** [comment]
I'm kind of amazed the site works at all on mobile, but this should be easy enough to implement!

**Comment by bspammer** [comment]
Fixed in https://github.com/bspammer/twitch-chat-replay/pull/121
